### ISSUE TITLE
你好，我使用这个主题提示错误：找不到Layout.vue

### ISSUE THREAD

**Issue by liulinboyi** [Bloss/vuepress-theme-yubisaki-example#1]
错误如下：
Error: [vuepress] Failed to load custom theme "yubisaki". File vuepress-theme-yubisaki/Layout.vue does not exist.
使用yarn install 安装的
nodejs 版本：10.15.1
vuepress版本：1.0.0-alpha.40
望解决，谢谢

通过全局安装vuepres 不提示 Error: [vuepress] Failed to load custom theme "yubisaki". File vuepress-theme-yubisaki/Layout.vue does not exist. 这个了 现在提示这个：
warning Cannot read property 'Page' of undefined
TypeError: Cannot read property 'multiple' of undefined

**Comment by stickmy** [comment]
有能复现的 repo 吗

**Comment by liulinboyi** [comment]
> 有能复现的repo吗

刚才试了试还是不行。
https://github.com/liulinboyi/vuepress-theme-yubisaki-debug

**Comment by liulinboyi** [comment]
> > 有能复现的repo吗
> 
> 刚才试了试还是不行。
> https://github.com/liulinboyi/vuepress-theme-yubisaki-debug

![image](https://user-images.githubusercontent.com/41336612/53642429-b73eee00-3c6c-11e9-916c-7f4fcaf2b186.png)

**Comment by stickmy** [comment]
排查了一下，这是由于最新版本 vuepress 的 themeAPI bug 引起的。
https://github.com/vuejs/vuepress/issues/1371

**Comment by stickmy** [comment]
workaround：

```json
"vuepress": "1.0.0-alpha.32",
"@vuepress/core": "1.0.0-alpha.32"
```
在项目根目录下更改并添加这两个版本，安装依赖之后:

`cd node_modules/vuepress`, `rm -rf node_modules`, 并且将 vuepress 的依赖改为 `@vuepress/core: 1.0.0-alpha.32`，在 vuepress 目录下执行 `npm install` 重新安装依赖。

回到项目根目录，`npm run dev`，跑起来了

**Comment by liulinboyi** [comment]
感谢回答，我的解决方法是：
全局安装vuepress指定版本
`cnpm i vuepress@1.0.0-alpha.35 -g` //这个不会直接安装指定版本还是会安装 1.0.0-alpha.40版本
所以只能去全局安装根目录 我的全局安装目录是：`C:\Users\小刘\AppData\Roaming\npm\node_modules\vuepress`
然后按照您的方法`rm -rf node_modules`
接着手动安装每一个依赖
(cnpm install 还是会安装 1.0.0-alpha.40版本 所以只能曲线救国 手动安装指定版本了)
`cnpm i @vuepress/core@1.0.0-alpha.35 `
`cnpm i @vuepress/theme-default@1.0.0-alpha.35`
`cnpm i @cac@6.3.9`
最后按照您的方法
回到项目根目录，`npm run dev`，跑起来了
**最后非常感谢您的回答！谢谢！**
![image](https://user-images.githubusercontent.com/41336612/53676425-12102e00-3cdd-11e9-8fc8-d6adf52b9654.png)
![image](https://user-images.githubusercontent.com/41336612/53676447-5d2a4100-3cdd-11e9-96cc-21773bc16824.png)
