### ISSUE TITLE
There is an error in the tags in your example, when you click the tags option, and then in the tag, it does not open anything.

### ISSUE THREAD

**Issue by farnetani** [Bloss/vuepress-theme-yubisaki-example#4]
There is an error in the tags in your example, when you click the tags option, and then in the tag, it does not open anything.

see: [image-reference](https://imgur.com/bpQ2fp6)

The error is when I click in tag, see image of error: 

[Image-of-error-your-example](https://imgur.com/s9knC1V)

Just download your own sample and run npm install and then run npm run and test.

**Comment by stickmy** [comment]
I've fixed this issue. Please re-clone this repo or update vuepress-theme-yubisaki and @yubisaki/plugin-xx version to fix it.
